### ISSUE TITLE
Make Voice Over Asset list

### ISSUE THREAD

**Issue by nharsch** [nharsch/Dial-ality#10]

**Comment by nharsch** [comment]
- [ ] create asset list
- [ ] email asset list to ListenToMelanie@gmail.com

**Comment by Talec** [comment]
Assets needed

- [ ] person hot 
- [ ] person cold
- [ ] person relieved

**Comment by nharsch** [comment]
@Talec Melanie sent this: https://wetransfer.com/downloads/bf15c08da19f08524ce8767012ab7f0720220130193207/93ab0e
